language: lisp
sudo: required

dist: bionic

env:
  matrix:
    - LISP=sbcl-bin TARGET=qlot
    - LISP=sbcl-bin TARGET=bundle

install:
  - |
    case "$TARGET" in 
      qlot)
        curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
        mkdir -p ~/.roswell/lisp/quicklisp/dists/pauldist
        curl -L http://pauldist.kisp.in/pauldist.txt > ~/.roswell/lisp/quicklisp/dists/pauldist/distinfo.txt
        touch  ~/.roswell/lisp/quicklisp/dists/pauldist/enabled.txt        
        ;;
      bundle)
        sudo apt-get install sbcl
        ;;
    esac
  - bundle install

script:
  - ./configure --prefix=/usr
  - make $TARGET-build
  - make cucumber
