# -*- mode:ruby -*-

require 'rubygems'
require 'rake/gempackagetask'

$<%(underscores ?gem-name)%>_version = "<%?initial-version%>"

spec = Gem::Specification.new do |s|
  s.name = %q{<%(underscores ?gem-name)%>}
  s.version = $<%(underscores ?gem-name)%>_version
  s.summary = "clnk is a lisp installer a la clbuild"
  # s.autorequire = %q{<%(underscores ?gem-name)%>}
  s.executables = ["<%(underscores ?gem-name)%>"]
  s.date = %q{<%(current-date)%>}
  candidates = Dir.glob("{bin,docs,lib,test}/**/*")
  s.files = candidates.delete_if do |item|
    item.include?("CVS") || item.include?("rdoc")
  end
  # puts "Files:"
  # puts s.files
  s.has_rdoc = true
  # s.extra_rdoc_files = ["README"]
  # s.rdoc_options = ["--line-numbers", "-m", "Clnk::CommandParser"]
  s.require_path = "lib"
  s.test_files = Dir.glob("test/*.rb")
  # s.add_dependency("cmdparse", ">= 2.0.2")
  # s.add_dependency("highline", ">= 1.4.0")
end

Rake::GemPackageTask.new(spec) do |pkg|
  # pkg.need_tar = true
end

task :default => ["pkg/<%(underscores ?gem-name)%>-#{$<%(underscores ?gem-name)%>_version}.gem"]

task "install" => ["pkg/<%(underscores ?gem-name)%>-#{$<%(underscores ?gem-name)%>_version}.gem"] do
  system("sudo gem install pkg/<%(underscores ?gem-name)%>-#{$<%(underscores ?gem-name)%>_version}.gem")
end

